export { TestPage } from "./TestPage/TestPage";
export { RawDataChartsPage } from "./RawDataChartsPage/RawDataChartsPage";
export { DataWOutliersChartsPage } from "./OutliersPage/DataWOutliersChartsPage";
export { MainPage } from "./MainPage/MainPage";
export { NotificationsPage } from "./NotificationsPage/NotificationsPage";
export { LoginPage } from "./AuthPage/AuthPage";
export { QRAuthPage } from "./QRAuthPage/QRAuthPage";
export { GoogleFitnessAuthPage } from "./GoogleFitnessAuthPage/GoogleFitnessAuthPage";
export { IntegrationStatusPage } from "./IntegrationStatusPage/IntegrationStatusPage";
export { MLPredictionsPage } from "./MLPredictionsPage/MLPredictionsPage";
export { GenerateReportPage } from "./GenerateReportPage/GenerateReportPage" 
export { GetFHIRDataQRPage } from "./GetFHIRDataQRPage/GetFHIRDataQRPage"